name: omics_toolbox
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - python=3.10
  - pip
  - typer
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy 
  - pandas=2.2.0
  - scikit-learn
  - ruff
  - scanpy 
  - python-igraph 
  - leidenalg
  - pip:
    - python-dotenv
    - mkdocs
    - -e .
    - mioflow
    - phate
    - meld