name: omics_toolbox
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - python=3.10
  - pip
  - typer
  - tqdm
  - ipython
  - jupyterlab
  - ipywidgets
  - matplotlib
  - seaborn
  - notebook
  - numpy 
  - pandas=2.2.0
  - scikit-learn
  - ruff
  - scanpy 
  - python-igraph 
  - leidenalg
  - loguru
  - pyarrow
  # torch packages
  - pytorch
  - torchvision
  - tensorboard
  - pip:
    - python-dotenv
    - mkdocs
    - -e .
    # Dim Changer dependencies
    - pytorch-lightning
    - hydra-core
    - omegaconf
    - hydra-colorlog
    - hydra-optuna-sweeper
    # Krishnaswamy Lab dependencies
    - mioflow
    - phate
    - meld
    - graphtools
    - magic-impute
    # MIOFlow related dependencies
    - POT
    - torchdiffeq
    - torchsde
    # Visualization
    - plotly3d


