[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "omics_toolbox"
version = "0.1.0"
description = "Central utility package for Krishnaswamy Lab multiomics tools."
authors = [
  { name = "Krishnaswamy Lab" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    # Krishnaswamy Lab packages
    "phate",
    "mioflow",
    "meld",
    "graphtools",
    # Core scientific stack
    "numpy",
    "pandas",
    "scanpy",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "seaborn",
    # Utilities
    "loguru",
    "requests",
    "tqdm",
    "gdown>=5.2.1",
    "ritini>=0.0.2",
]

[project.optional-dependencies]
notebooks = [
    "jupyterlab",
    "notebook",
    "ipywidgets",
]
dev = [
    "ruff",
    "jupyterlab",
]


[tool.ruff]
line-length = 99
src = ["omics_toolbox"]
include = ["pyproject.toml", "omics_toolbox/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["omics_toolbox"]
force-sort-within-sections = true
